version: "3.4"
services:
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    restart: unless-stopped
    volumes:
      - ./qdrant/data:/qdrant/storage # download folder
